### ISSUE TITLE
Open File Dialog Crashing App on Windows

### ISSUE THREAD

**Issue by kmgill** [kmgill/solhat-egui#1]
Intermittent issue, appears to be an unaddressed issue within [rfd](https://github.com/PolyMeilex/rfd)

```
thread 'main' panicked at C:\Users\kmsmg\.cargo\registry\src\index.crates.io-6f17d22bba15001f\winit-0.28.7\src\platform_impl\windows\event_loop\runner.rs:245:18:
either event handler is re-entrant (likely), or no event handler is registered (very unlikely)
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\std\src\panicking.rs:595
   1: core::panicking::panic_fmt
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\core\src\panicking.rs:67
   2: core::panicking::panic_display
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\core\src\panicking.rs:150
   3: core::panicking::panic_str
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\core\src\panicking.rs:134
   4: core::option::expect_failed
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\core\src\option.rs:1988
   5: enum2$<core::option::Option<alloc::boxed::Box<dyn$<core::ops::function::FnMut<tuple$<enum2$<winit::event::Event<enum2$<eframe::native::run::UserEvent> > >,ref_mut$<enum2$<winit::event_loop::ControlFlow> > >,assoc$<Output,tuple$<> > > >,alloc::alloc::Globa
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33\library\core\src\option.rs:898
   6: winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure$0<enum2$<eframe::native::run::UserEvent> >
             at C:\Users\kmsmg\.cargo\registry\src\index.crates.io-6f17d22bba15001f\winit-0.28.7\src\platform_impl\windows\event_loop\runner.rs:244
   7: core::panic::unwind_safe::impl$23::call_once<tuple$<>,winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure_env$0<enum2$<eframe::native::run::UserEvent> > >
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33\library\core\src\panic\unwind_safe.rs:271
   8: std::panicking::try::do_call<core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure_env$0<enum2$<eframe::native::run::UserEvent> > >,tuple$<> >
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33\library\std\src\panicking.rs:502
   9: eframe::native::run::with_event_loop::EVENT_LOOP::__getit::closure$0
  10: std::panicking::try<tuple$<>,core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure_env$0<enum2$<eframe::native::run::UserEvent> > > >
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33\library\std\src\panicking.rs:466
  11: std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure_env$0<enum2$<eframe::native::run::UserEvent> > >,tuple$<> >
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33\library\std\src\panic.rs:142
  12: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<enum2$<eframe::native::run::UserEvent> >::catch_unwind<enum2$<eframe::native::run::UserEvent>,tuple$<>,winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::clos
             at C:\Users\kmsmg\.cargo\registry\src\index.crates.io-6f17d22bba15001f\winit-0.28.7\src\platform_impl\windows\event_loop\runner.rs:157
  13: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<enum2$<eframe::native::run::UserEvent> >::call_event_handler<enum2$<eframe::native::run::UserEvent> >
             at C:\Users\kmsmg\.cargo\registry\src\index.crates.io-6f17d22bba15001f\winit-0.28.7\src\platform_impl\windows\event_loop\runner.rs:242
  14: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<enum2$<eframe::native::run::UserEvent> >::call_new_events<enum2$<eframe::native::run::UserEvent> >
             at C:\Users\kmsmg\.cargo\registry\src\index.crates.io-6f17d22bba15001f\winit-0.28.7\src\platform_impl\windows\event_loop\runner.rs:398
  15: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<enum2$<eframe::native::run::UserEvent> >::move_state_to<enum2$<eframe::native::run::UserEvent> >
             at C:\Users\kmsmg\.cargo\registry\src\index.crates.io-6f17d22bba15001f\winit-0.28.7\src\platform_impl\windows\event_loop\runner.rs:333
  16: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<enum2$<eframe::native::run::UserEvent> >::poll<enum2$<eframe::native::run::UserEvent> >
             at C:\Users\kmsmg\.cargo\registry\src\index.crates.io-6f17d22bba15001f\winit-0.28.7\src\platform_impl\windows\event_loop\runner.rs:206
  17: winit::platform_impl::platform::event_loop::thread_event_target_callback::closure$0<enum2$<eframe::native::run::UserEvent> >
             at C:\Users\kmsmg\.cargo\registry\src\index.crates.io-6f17d22bba15001f\winit-0.28.7\src\platform_impl\windows\event_loop.rs:2541
  18: core::ops::function::FnOnce::call_once<winit::platform_impl::platform::event_loop::thread_event_target_callback::closure_env$0<enum2$<eframe::native::run::UserEvent> >,tuple$<> >     
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33\library\core\src\ops\function.rs:250
  19: core::panic::unwind_safe::impl$23::call_once<isize,winit::platform_impl::platform::event_loop::thread_event_target_callback::closure_env$0<enum2$<eframe::native::run::UserEvent> > >  
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33\library\core\src\panic\unwind_safe.rs:271
  20: std::panicking::try::do_call<core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::thread_event_target_callback::closure_env$0<enum2$<eframe::native::run::UserEvent> > >,isize>
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33\library\std\src\panicking.rs:502
  21: eframe::native::run::with_event_loop::EVENT_LOOP::__getit::closure$0
  22: std::panicking::try<isize,core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::thread_event_target_callback::closure_env$0<enum2$<eframe::native::run::UserEvent> > > >
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33\library\std\src\panicking.rs:466
  23: std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::thread_event_target_callback::closure_env$0<enum2$<eframe::native::run::UserEvent> > >,isize>
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33\library\std\src\panic.rs:142
  24: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<enum2$<eframe::native::run::UserEvent> >::catch_unwind<enum2$<eframe::native::run::UserEvent>,isize,winit::platform_impl::platform::event_loop::thread_event_target_callback::closure_env$0
             at C:\Users\kmsmg\.cargo\registry\src\index.crates.io-6f17d22bba15001f\winit-0.28.7\src\platform_impl\windows\event_loop\runner.rs:157
  25: winit::platform_impl::platform::event_loop::thread_event_target_callback<enum2$<eframe::native::run::UserEvent> >
             at C:\Users\kmsmg\.cargo\registry\src\index.crates.io-6f17d22bba15001f\winit-0.28.7\src\platform_impl\windows\event_loop.rs:2547
  26: CallWindowProcW
  27: DispatchMessageW
  28: Ordinal206
  29: Ordinal206
  30: Ordinal850
  31: Ordinal850
  32: ReadCabinetState
  33: Ordinal792
  34: Ordinal778
  35: Ordinal778
  36: Ordinal61
  37: Ordinal61
  38: Ordinal61
  39: Ordinal778
  40: GetFileTitleW
  41: GetFileTitleW
  42: GetFileTitleW
  43: ScreenToClient
  44: ScreenToClient
  45: ScreenToClient
  46: CallWindowProcW
  47: DispatchMessageW
  48: SendMessageTimeoutW
  49: KiUserCallbackDispatcher
  50: NtUserMessageCall
  51: SendMessageW
  52: CreateWindowInBandEx
  53: DialogBoxIndirectParamAorW
  54: DialogBoxIndirectParamAorW
  55: DialogBoxIndirectParamW
  56: DllCanUnloadNow
  57: GetFileTitleW
  58: enum2$<rfd::backend::win_cid::file_dialog::dialog_ffi::DialogInner>::show
             at C:\Users\kmsmg\.cargo\registry\src\index.crates.io-6f17d22bba15001f\rfd-0.12.1\src\backend\win_cid\file_dialog\dialog_ffi.rs:117
  59: rfd::backend::win_cid::file_dialog::dialog_ffi::IDialog::show
             at C:\Users\kmsmg\.cargo\registry\src\index.crates.io-6f17d22bba15001f\rfd-0.12.1\src\backend\win_cid\file_dialog\dialog_ffi.rs:280
  60: rfd::backend::win_cid::file_dialog::impl$0::pick_file::run::closure$0
             at C:\Users\kmsmg\.cargo\registry\src\index.crates.io-6f17d22bba15001f\rfd-0.12.1\src\backend\win_cid\file_dialog.rs:26
  61: rfd::backend::win_cid::utils::init_com<enum2$<core::result::Result<std::path::PathBuf,i32> >,rfd::backend::win_cid::file_dialog::impl$0::pick_file::run::closure_env$0>
             at C:\Users\kmsmg\.cargo\registry\src\index.crates.io-6f17d22bba15001f\rfd-0.12.1\src\backend\win_cid\utils.rs:28
  62: rfd::backend::win_cid::file_dialog::impl$0::pick_file::run
             at C:\Users\kmsmg\.cargo\registry\src\index.crates.io-6f17d22bba15001f\rfd-0.12.1\src\backend\win_cid\file_dialog.rs:24
  63: rfd::backend::win_cid::file_dialog::impl$0::pick_file
             at C:\Users\kmsmg\.cargo\registry\src\index.crates.io-6f17d22bba15001f\rfd-0.12.1\src\backend\win_cid\file_dialog.rs:30
  64: rfd::file_dialog::FileDialog::pick_file
             at C:\Users\kmsmg\.cargo\registry\src\index.crates.io-6f17d22bba15001f\rfd-0.12.1\src\file_dialog.rs:103
  65: solhat_egui::impl$1::inputs_frame_contents::closure$0
             at .\src\main.rs:466
  66: core::ops::function::FnOnce::call_once<solhat_egui::impl$1::inputs_frame_contents::closure_env$0,tuple$<ref_mut$<egui::ui::Ui> > >
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33\library\core\src\ops\function.rs:250
  67: alloc::boxed::impl$47::call_once<tuple$<ref_mut$<egui::ui::Ui> >,dyn$<core::ops::function::FnOnce<tuple$<ref_mut$<egui::ui::Ui> >,assoc$<Output,tuple$<> > > >,alloc::alloc::Global>   
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33\library\alloc\src\boxed.rs:2007
  68: egui::grid::impl$4::show_dyn::closure$3::closure$0<tuple$<> >
             at C:\Users\kmsmg\.cargo\registry\src\index.crates.io-6f17d22bba15001f\egui-0.23.0\src\grid.rs:442
  69: core::ops::function::FnOnce::call_once<egui::grid::impl$4::show_dyn::closure$3::closure_env$0<tuple$<> >,tuple$<ref_mut$<egui::ui::Ui> > >
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33\library\core\src\ops\function.rs:250
  70: alloc::boxed::impl$47::call_once<tuple$<ref_mut$<egui::ui::Ui> >,dyn$<core::ops::function::FnOnce<tuple$<ref_mut$<egui::ui::Ui> >,assoc$<Output,tuple$<> > > >,alloc::alloc::Global>   
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33\library\alloc\src\boxed.rs:2007
  71: egui::ui::Ui::allocate_ui_with_layout_dyn<tuple$<> >
             at C:\Users\kmsmg\.cargo\registry\src\index.crates.io-6f17d22bba15001f\egui-0.23.0\src\ui.rs:888
  72: egui::ui::Ui::horizontal_with_main_wrap_dyn<tuple$<> >
             at C:\Users\kmsmg\.cargo\registry\src\index.crates.io-6f17d22bba15001f\egui-0.23.0\src\ui.rs:1918
  73: egui::ui::Ui::horizontal<tuple$<>,egui::grid::impl$4::show_dyn::closure$3::closure_env$0<tuple$<> > >
             at C:\Users\kmsmg\.cargo\registry\src\index.crates.io-6f17d22bba15001f\egui-0.23.0\src\ui.rs:1846
  74: egui::grid::impl$4::show_dyn::closure$3<tuple$<> >
             at C:\Users\kmsmg\.cargo\registry\src\index.crates.io-6f17d22bba15001f\egui-0.23.0\src\grid.rs:422
  75: egui::ui::Ui::allocate_ui_at_rect<tuple$<>,egui::grid::impl$4::show_dyn::closure_env$3<tuple$<> > >
             at C:\Users\kmsmg\.cargo\registry\src\index.crates.io-6f17d22bba15001f\egui-0.23.0\src\ui.rs:909
  76: egui::grid::Grid::show_dyn<tuple$<> >
             at C:\Users\kmsmg\.cargo\registry\src\index.crates.io-6f17d22bba15001f\egui-0.23.0\src\grid.rs:420
  77: egui::grid::Grid::show<tuple$<>,solhat_egui::impl$1::inputs_frame_contents::closure_env$0>
             at C:\Users\kmsmg\.cargo\registry\src\index.crates.io-6f17d22bba15001f\egui-0.23.0\src\grid.rs:390
  78: solhat_egui::SolHat::inputs_frame_contents
             at .\src\main.rs:461
  79: solhat_egui::impl$1::on_update::closure$0::closure$0
             at .\src\main.rs:284
  80: egui::ui::impl$6::add_enabled_ui::closure$0<tuple$<>,solhat_egui::impl$1::on_update::closure$0::closure_env$0>
             at C:\Users\kmsmg\.cargo\registry\src\index.crates.io-6f17d22bba15001f\egui-0.23.0\src\ui.rs:1145
  81: core::ops::function::FnOnce::call_once<egui::ui::impl$6::add_enabled_ui::closure_env$0<tuple$<>,solhat_egui::impl$1::on_update::closure$0::closure_env$0>,tuple$<ref_mut$<egui::ui::Ui> > >
  82: alloc::boxed::impl$47::call_once<tuple$<ref_mut$<egui::ui::Ui> >,dyn$<core::ops::function::FnOnce<tuple$<ref_mut$<egui::ui::Ui> >,assoc$<Output,tuple$<> > > >,alloc::alloc::Global>
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33\library\alloc\src\boxed.rs:2007
  83: egui::ui::Ui::scope_dyn<tuple$<> >
             at C:\Users\kmsmg\.cargo\registry\src\index.crates.io-6f17d22bba15001f\egui-0.23.0\src\ui.rs:1731
  84: egui::ui::Ui::scope<tuple$<>,egui::ui::impl$6::add_enabled_ui::closure_env$0<tuple$<>,solhat_egui::impl$1::on_update::closure$0::closure_env$0> >
             at C:\Users\kmsmg\.cargo\registry\src\index.crates.io-6f17d22bba15001f\egui-0.23.0\src\ui.rs:1719
  85: egui::ui::Ui::add_enabled_ui<tuple$<>,solhat_egui::impl$1::on_update::closure$0::closure_env$0>
             at C:\Users\kmsmg\.cargo\registry\src\index.crates.io-6f17d22bba15001f\egui-0.23.0\src\ui.rs:1143
  86: solhat_egui::impl$1::on_update::closure$0
             at .\src\main.rs:283
  87: core::ops::function::FnOnce::call_once<solhat_egui::impl$1::on_update::closure_env$0,tuple$<ref_mut$<egui::ui::Ui> > >
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33\library\core\src\ops\function.rs:250
  88: alloc::boxed::impl$47::call_once<tuple$<ref_mut$<egui::ui::Ui> >,dyn$<core::ops::function::FnOnce<tuple$<ref_mut$<egui::ui::Ui> >,assoc$<Output,tuple$<> > > >,alloc::alloc::Global>
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33\library\alloc\src\boxed.rs:2007
  89: egui::containers::panel::impl$3::show_inside_dyn::closure$6<tuple$<> >
             at C:\Users\kmsmg\.cargo\registry\src\index.crates.io-6f17d22bba15001f\egui-0.23.0\src\containers\panel.rs:277
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
2023-10-25 08:20:14.834 INFO C:\Users\kmsmg\.cargo\git\checkouts\solhat-5269b4064ab5687b\b1555e9\src\ser.rs:226 Extracting image frame #0 of 1081 from E:\Data\Astrophotography\Sun\2023-10-10\Sun_113855.ser. Size 4708352 at byte index 178
2023-10-25 08:20:15.749 INFO C:\Users\kmsmg\.cargo\git\checkouts\solhat-5269b4064ab5687b\b1555e9\src\ser.rs:226 Extracting image frame #0 of 1081 from E:\Data\Astrophotography\Sun\2023-10-10\Sun_113855.ser. Size 4708352 at byte index 178
2023-10-25 08:20:16.200 INFO src\state.rs:47 Last opened path: "E:\\Data\\Astrophotography\\Sun\\2023-10-10\\Sun_113855.ser"
error: process didn't exit successfully: `target\debug\solhat-egui.exe` (exit code: 101)
```

**Comment by kmgill** [comment]
Looks like it in an issue with the file dialog clashing with the repaint request. If that line (`ctx.request_repaint_after(Duration::from_millis(10));`) is commented out, the crash no longer happens.

This causes a small dilemma, however, as the main window will not auto repaint to reflect updates in the processing once the stacking reaches 100%. This is because the animated progress bar no longer animates. This can be addressed, however, by adding a basic spinner that runs while the processing thread is active.

**Comment by kmgill** [comment]
Fixed with referenced commit.
